name: Check Space
description: Reusable step that prints disk usage information
runs:
  using: "composite"
  steps:
    - name: Check Space
      shell: bash
      run: |
        if test -d /nix/store; then
          sudo du -hs /nix/store/* | sort -h | tail -n 10
        fi
        echo ===============
        df -h
        echo ===============
        du -hs ~/* | sort -h
        echo ===============
        du -hs * | sort -h
        echo ===============
        du -hs /home/runner/runners/* | sort -h
        echo ===============
        du -hs /home/runner/work/* | sort -h
        echo ===============
