/* Generated by Yosys 0.33 (git sha1 2584903a060, clang++ 11.1.0 -fPIC -Os) */

module inverter(in, out);
  input in;
  wire in;
  output out;
  wire out;
  sky130_fd_sc_hd__inv_2 _0_ (
    .A(in),
    .Y(out)
  );
endmodule
