name: Build/Cache Nix
description: Builds default devShell for a platform, caching the results (if applicable)
inputs:
  cachix_cache:
    description: "The name of the Cachix cache to download to and/or upload from"
    required: true
    default: "openlane"
  cachix_token:
    description: "An authentication token for Cachix"
    required: false
    default: ""
  shell:
    description: "Shell to use"
    required: true
    default: "bash"
  nix_system:
    description: "The nix platform string to build for"
    required: true
    default: "x86_64-linux"
  local_cache_key:
    description: Key to use for the cache
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - id: cache
      name: Cache Derivation
      uses: actions/cache@v3
      with:
        key: ${{ inputs.local_cache_key }}-${{ inputs.nix_system }}
        path: /tmp/${{ inputs.local_cache_key }}
    - id: Build
      name: Build
      shell: ${{ inputs.shell }}
      run: |
        substituters='https://${{ inputs.cachix_cache }}.cachix.org https://cache.nixos.org'
        if [ '${{ inputs.local_cache_key }}' = '' ]; then
          substituters="file:///tmp/${{ inputs.local_cache_key }} $substituters"
        fi
        echo "#################################################################"
        outPath=$(nix build\
          --print-out-paths\
          --no-link\
          --accept-flake-config\
          --option substituters "$substituters"\
          .#devShells.${{ inputs.nix_system }}.default )
        echo "out-path=$outPath" >> $GITHUB_OUTPUT
        sudo du -hs /nix/store/* | sort -h | tail -n 20
    - name: Unit/Step Tests
      shell: ${{ inputs.shell }}
      run: |
        echo "#################################################################"
        nix develop .#devShells.${{ inputs.nix_system }}.default --accept-flake-config --command pytest --step-rx '.' -n auto
    - name: Smoke Test
      shell: ${{ inputs.shell }}
      run: |
        echo "#################################################################"
        nix run .#packages.${{ inputs.nix_system }}.openlane -- --smoke-test
    - name: Push to local cache
      shell: ${{ inputs.shell }}
      if: ${{ inputs.local_cache_key != '' && steps.cache.outputs.cache-hit != 'true' }}
      run: |
        nix copy\
          --to 'file:///tmp/${{ inputs.local_cache_key }}?compression=zstd&parallel-compression=true'\
          ${{ steps.build.outputs.out-path }}
    - name: Install + Push to Cachix
      shell: ${{ inputs.shell }}
      if: ${{ inputs.cachix_token != '' }}
      run: |
        echo "#################################################################"
        nix-env -iA cachix -f https://cachix.org/api/v1/install
        cachix authtoken ${{ inputs.cachix_token }}
        cachix push ${{ inputs.cachix_cache }} ${{ steps.build.outputs.out-path }}
