name: Set up Nix
description: Sets up the Nix package manager and the OpenLane binary cache
inputs:
  cachix_cache:
    description: "The name of the Cachix cache to download to and/or upload from"
    required: true
    default: "openlane"
  cachix_token:
    description: "An authentication token for Cachix"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - uses: DeterminateSystems/nix-installer-action@main
    - name: Check Space
      if: ${{ always() }}
      uses: ./.github/actions/check_space
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Check Space
      if: ${{ always() }}
      uses: ./.github/actions/check_space
    - name: Setup Cachix
      uses: cachix/cachix-action@v13
      with:
        name: ${{ inputs.cachix_cache }}
        authToken: "${{ inputs.cachix_token }}"
