name: Set up Nix
description: Sets up the Nix package manager and the OpenLane binary cache
inputs:
  cachix_cache:
    description: "The name of the Cachix cache to download to and/or upload from"
    required: true
    default: "openlane"
  cachix_token:
    description: "An authentication token for Cachix"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Setup Nix
      uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:22.11
    - name: Setup Cachix
      uses: cachix/cachix-action@v12
      with:
        name: ${{ inputs.cachix_cache }}
        authToken: "${{ inputs.cachix_token }}"
