- scl: sky130A/sky130_fd_sc_hd
  name: fastest_test_set
  designs:
    - inverter
    - wbqspiflash
    - APU
    - s44
    - zipdiv
    - blink
    - name: xtea
      config_file: config.tcl
    - usb
    - usb_cdc_core
    - name: latch
      config_file: config_good.json
    - name: latch
      config_file: config_bad.json
    - spm
    - gcd
    - caravel_upw
    - io_placer
    - test_sram_macro
    - manual_macro_placement_test
- scl: sky130A/sky130_fd_sc_hd
  name: extended_test_set
  designs:
    - BM64
    - salsa20
    - aes_core
    - blabla
    - picorv32a
    - PPU
    - y_huff
    - aes
- scl: gf180mcuD/gf180mcu_fd_sc_mcu7t5v0
  name: fastest_test_set
  designs:
    - spm
    - APU
    - usb
    - usb_cdc_core
    - zipdiv
    - blink
    - wbqspiflash
    - name: latch
      config_file: config_good.json
    - name: latch
      config_file: config_bad.json
- scl: gf180mcuD/gf180mcu_fd_sc_mcu7t5v0
  name: extended_test_set
  designs:
    - picorv32a
    - PPU
    - y_huff
