name: Set up environment
description: Sets up the repo and a number of environment variables that are useful for the CI.
runs:
  using: "composite"
  steps:
    - name: Check out Git repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Export Repo URL
      shell: bash
      run: echo "REPO_URL=https://github.com/${{ github.repository }}.git" >> $GITHUB_ENV

    - name: Export PDK ROOT
      shell: bash
      run: echo "PDK_ROOT=/usr/local/pdk" >> $GITHUB_ENV

    - name: Export Branch Name
      shell: bash
      run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Set default for env.NEW_TAG
      shell: bash
      run: echo "NEW_TAG=NO_NEW_TAG" >> $GITHUB_ENV

    - name: Check for new version
      if: ${{ env.BRANCH_NAME == 'ci-test' }}
      shell: bash
      run: |
        make venv
        cd ${GITHUB_WORKSPACE}/ && ./venv/bin/python3 .github/scripts/generate_tag.py

    - name: Publish
      if: ${{ github.event_name == 'push' && env.BRANCH_NAME == 'ci-test' && env.TAG != 'NO_NEW_TAG' }}
      shell: bash
      run: |
        echo "PUBLISH=1" >> $GITHUB_ENV
